parameters:
#    controlcar_journal.example.class: Controlcar\JournalBundle\Example

services:
#    controlcar_journal.example:
#        class: %controlcar_journal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
